# Generated by Django 4.1.1 on 2022-09-13 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=10)),
                ('question_text', models.TextField()),
                ('slug_text', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='class_grades')),
                ('teacher', models.ManyToManyField(to='accounts.teacherprofile')),
            ],
        ),
    ]
