# Generated by Django 4.1.1 on 2022-09-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_classgrade_teacher_classgrade_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('type', models.BooleanField()),
                ('difficulty', models.CharField(max_length=10)),
                ('question_text', models.TextField()),
            ],
        ),
    ]
