# Generated by Django 4.1.1 on 2022-09-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
