# Generated by Django 4.1.1 on 2022-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_questions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='slug_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
