# Generated by Django 4.1.1 on 2022-09-13 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(help_text='Enter your email address', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid email address', regex='^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$')]),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Please enter a valid Pakistan phone number', regex='^((\\+92)?(0092)?(92)?(0)?)(3)([0-9]{9})$')]),
        ),
    ]
