# Generated by Django 4.1.1 on 2022-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacherprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(help_text='Enter your email address', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
